### ISSUE TITLE
Array size issue

### ISSUE THREAD

**Issue by DiDeoxy** [ChuanyiZ/vef#2]
Hi. I am using VEF with nextflow and get the following error:

```Error executing process > 'vef_indels:vef_clf (null)'
Caused by:
  Process `vef_indels:vef_clf (null)` terminated with an error exit status (1)
Command executed:

  python ~/vef/example/vef_clf.py \    --happy happy_cohort_INDEL.vcf.gz \
    --target cohort_INDEL.vcf \
    --mode INDEL

Command exit status:
  1
Command output:
  (empty)

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  /home/maxh/conda/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
    warnings.warn(msg, category=DeprecationWarning)
  /home/maxh/conda/lib/python3.7/site-packages/allel/io/vcf_read.py:1745: UserWarning: multiple INFO headers for 'AF'
    warnings.warn('multiple INFO headers for %r' % k)
  INFO    2019-12-02 22:59:59,961 VCFDataset      Start extracting label from happy_cohort_INDEL.vcf.gz
  INFO    2019-12-02 23:00:04,174 VCFDataset      Total variants(hap.py): 677102, in high-conf region variants: 534684
  INFO    2019-12-02 23:00:05,958 VCFDataset      Finish extracting label from file
  INFO    2019-12-02 23:00:06,649 VCFDataset      Start extracting variants from cohort_INDEL.vcf
  Traceback (most recent call last):
    File "/home/maxh/vef/example/vef_clf.py", line 49, in <module>
      main()
    File "/home/maxh/vef/example/vef_clf.py", line 41, in main
      dataset = VCFDataset(vcf_hap, vcf_tgt, mode)
    File "/home/maxh/conda/lib/python3.7/site-packages/vef/core.py", line 94, in __init__
      self._compare(mode)
    File "/home/maxh/conda/lib/python3.7/site-packages/vef/core.py", line 168, in _compare
      self.dataset[ch] = np.vstack((annotes_chrom[ch][1:, annotes_idx], label_list[ch][1, label_idx])).transpose()
    File "<__array_function__ internals>", line 6, in vstack
    File "/home/maxh/conda/lib/python3.7/site-packages/numpy/core/shape_base.py", line 282, in vstack
      return _nx.concatenate(arrs, 0)
    File "<__array_function__ internals>", line 6, in concatenate
  ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3697 and the array at index 1 has size 3696

Work dir:
  /data/nextflow_temp/f4/336d6bf54b346e71b4a7e6ba646458

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line```

The cohort vcf file has multiple samples in it, I'm not sure if that's important.

Cheers.

**Comment by shivangi19999** [comment]
hi, i am running the code given on this github
I am facing the following issue please  have a look at it
python vef_apl.py
/home/xxxxx/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
usage: vef_apl.py [-h] --clf_file CLF_FILE --subject SUBJECT --suffix SUFFIX
                  --mode {SNP}
vef_apl.py: error: the following arguments are required: --clf_file, --subject, --suffix, --mode
2. python2 hap.py HG001_GRCh38_1_22_v4.2.1_benchmark.vcf Output_snp_try.vcf -f HG001_GRCh38_1_22_v4.2.1_benchmark.bed -o compare.snp.vcf -r GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta --no-roc
/usr/bin/python2: can't find '__main__' module in 'hap.py'
which version of joblib are they asking for and how the hap.py tool is used in this. please explain
